- hosts: target_servers
  become: yes
  become_method: sudo
  tasks:
  - name: apache2 is installed
    apt:
      name: apache2
      state: present
  - name: apache2 is running and enabled
    service:
      name: apache2
      state: started
      enabled: yes
