- hosts: target_servers
  become: yes
  become_method: sudo
  tasks:
  - name: General packages are installed
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - tar
      - wget
      - unzip
    tags: General_Packages
