- name: nginx is installed
  apt:
    name: "{{ nginx_package }}"
    state: present
  tags: install_nginx

- name: edit nginx.default
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: "server_name _;"
    line: "server_name {{ ansible_fqdn }};"
  tags: edit_nginx.default

- name: nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: put index.html
  copy:
    src: index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: 0644

- name: check nginx
  uri:
    url: http://{{ ansible_fqdn }}
