- name: mariadb is installed
  apt:
    name: "{{ mariadb_package }}"
    state: present
  tags: install_mariadb

- name: mariadb is running and enabled
  service:
    name: mariadb
    state: started
    enabled: yes
